INSERT INTO games (
  name,
  rules,
  hint,
  points_to_reach_level_1,
  points_to_reach_level_2,
  points_to_reach_level_3,
  nb_try_max_level_1,
  nb_try_max_level_2,
  nb_try_max_level_3 )
VALUES
  ('Temperature', 'Convert Fahrenheit into Celsius and Celsius into Fahrenheit!', '1°F = ( 1°C x 1.8 ) + 32 & 1°C = ( 1°F - 32 ) / 1.8', 5, 10, 15, 10, 15, 20),
  ('Weight', 'Convert Kilograms into Pounds and Pounds into Kilograms!', '1 kg = 2.2 lb & 1 lb = 0.45 kg', 10, 17, 25, 20, 30, 35),
  ('Distances', 'Convert Kilometers into Miles and Miles into Kilometers!', '1 mile = 1.61 km & 1 km = 0,62 mile', 7, 15, 20, 14, 25, 30),
  ('Length', 'Convert Centimeters into Inches and Inches into Centimeters!', '1 cm = 0.39 inche & 1 inche = 2.54 cm', 7, 15, 20, 14, 25, 30),
  ('General Knowledge', 'Find the right answer!', 'x', 7, 15, 30, 14, 25, 35),
  ('Flags', 'Which Flag represents which country?', 'x', 7, 15, 30, 14, 25, 35);

INSERT INTO knowledge (
  level,
  question,
  response,
  possible_res_1,
  possible_res_2,
  possible_res_3 )
VALUES
  (1, 'Which one of the following countries is on the border with Portugal?', 'Spain', 'France', 'Italy', 'Greece'),
  (1, 'Which one of the following countries is on the border with Luxembourg?', 'Belgium', 'Netherlands', 'Malta', 'Finland'),
  (1, 'Which one of the following countries is on the border with Lithuania?', 'Latvia', '	Estonia', 'Ukraine', 'Slovakia'),
  (1, 'Which one of the following countries is on the border with Netherlands?', 'Germany', '	Luxembourg', 'France', 'Denmark'),
  (1, 'Which one of the following countries is not on the border with Hungary?', 'Bosnia and Herzegovina', 'Slovakia', 'Autria', 'Romania'),
  (1, 'Which one of the following countries is not on the border with Finland?', 'Estonia', 'Norway', 'Sweden', 'Russia'),
  (1, 'Which one of the following countries is not on the border with Germany?', 'Slovenia', 'Czech Republic', 'Poland', 'Denmark'),
  (1, 'Which one of the following countries is not on the border with Autria?', 'France', 'Switzerland', 'Czech Republic', 'Hungary'),
  (1, 'What is the capital of Poland?', 'Warsaw', 'Glasgow', 'Budapest', 'Madrid'),
  (1, 'What is the capital of Romania?', 'Bucharest', 'Warsaw', 'Budapest', 'Budapest'),
  (1, 'What is the capital of Ireland?', 'Dublin', 'Berlin', 'London', 'Bratislava'),
  (1, 'What is the capital of Switzerland?', 'Bern', 'Vienna', 'Berlin', 'Paris'),
  (1, 'Is which country is located Nice?', 'France', 'Glasgow', 'Budapest', 'Madrid'),
  (1, 'Is which country is located Graz?', 'Austria', 'Hungary', 'Cyprus', 'Bulgaria'),
  (1, 'Is which country is located Milan?', 'Italy', 'Autria', 'Malta', 'Cyprus'),
  (1, 'Is which country is located Prague?', 'Czech Republic', 'Hungary', '	Lithuania', '	Latvia'),
  (1, 'Which one of these countries does not use Euro?', 'Sweden', 'Greece', 'Latvia', 'Slovakia'),
  (1, 'What is the first religion in Europe?', 'Catholic', 'Protestant', 'Orthodox', 'Muslim'),
  (1, 'What is the population of Europe?', 'Between 700 and 800 millions', 'Between 800 and 900 millions''Between 600 and 700 millions''Between 500 and 600 millions'),
  (1, 'What band consisted of members John, Paul, George, and Ringo?', 'The Beatles', 'The Rolling Stones', 'Oasis', 'U2'),
  (2, 'What is the second religion in Europe?', 'Orthodox', 'Protestant', 'Catholic', 'Muslim'),
  (2, 'Which Nordic Country does not have its own army?', 'Iceland', 'Norway', 'Sweden', 'Denmark'),
  (2, 'From what country did the traditional cuisine Goulash originate?', 'Hungary', 'Latvia', 'Estonia', 'Ukraine'),
  (2, 'What is the longest European river', 'Volga', 'Danube', 'Ural', 'Dnieper'),
  (2, 'Which museum is the most visited in Europe?', 'Louvre', 'Pergamon', 'The British Museum', 'The Natural History Museum', 'Royal Museum of Edinburgh'),
  (2, 'What is the disciplien of Novak Djokovic?', 'Tennis', 'Soccer', 'Golf', 'Basketball'),
  (2, 'What is the highest peak in Europe?', 'Mount Elbrus', 'Mont Blanc', 'Monte Rosa', 'Mount Olympus'),
  (2, 'How is called the largest beer festival of the world?', 'Oktoberfest', 'Octobeerfest', 'Okhtobeerfast', 'Octobearfeest'),
  (2, 'What is the smallest country in Europe?', 'Vatican', 'Switzerland', 'Luxembourg', 'Cyprus'),
  (2, 'How is called the famous small but indomitable Gaul with a yellow moustache?', 'Asterix', 'Obelix', 'Milou', 'Vercingetorix'),
  (2, ),
  (2, ),
  (2, ),
  (2, ),
  (2, ),
  (2, ),
  (2, ),
  (2, ),
  (2, ),
  (2, 'Which city hosted the 1992 Summer Olympic Games?', 'Barcelona', 'Paris', 'Lisbon', 'Athens'),
  (3, 'Portoferraio is the largest city on which Mediterranean island?', 'Elba'),
  (3, 'Which Nordic Country does not have its own army?', 'Iceland'),
  (3, 'In which famous play did a character say: Something is rotten in the state of Denmark?', 'Hamlet'),
  (3, 'Which French painter painted the art piece "The Luncheon on the Grass"?', 'Édouard Manet', 'Étienne Martin', 'Charles Monnet', 'Gustave Morin'),
  (3, 'Who is the Roman equivalent of Aphrodite', 'Venus', 'Trivia', 'Tellus', 'Vesta'),
  (3, 'What country has won the Eurovision Song Contest the most times?', 'Ireland', 'France', 'Portugal', 'United Kingdom'),
  (3, 'How many european soldiers were mobilised from 1914 to 1918 during the World War I?', 'Between 65 and 70 Millions', 'Between 60 and 65 Millions', 'Between 55 and 60 Millions', 'Between 70 and 75 Millions'),
  (3, ),
  (3, ),
  (3, ),
  (3, ),
  (3, ),
  (3, ),
  (3, ),
  (3, ),
  (3, ),
  (3, ),
  (3, ),
  (3, ),
  (3, );

INSERT INTO flags (
  level,
  response,
  possible_res_1,
  possible_res_2,
  possible_res_3 )
VALUES
  (1, 'Belgium', 'France', 'Monaco', 'Netherlands'),
  (1, 'Denmark', 'Belgium', 'Spain', 'Monaco'),
  (1, 'Finland', 'Greece', 'Belgium', 'Spain'),
  (1, 'France', 'Spain', 'Finland', 'Belgium'),
  (1, 'Germany', 'Denmark', 'Sweden', 'Norway'),
  (1, 'Greece', 'Ireland', 'Denmark', 'Finland'),
  (1, 'Ireland', 'Sweden', 'Portugal', 'Denmark'),
  (1, 'Luxembourg', 'Finland', 'France', 'Portugal'),
  (1, 'Monaco', 'Luxembourg', 'Greece', 'France'),
  (1, 'Netherlands', 'Germany', 'Luxembourg', 'Sweden'),
  (1, 'Norway', 'Monaco', 'Ireland', 'Greece'),
  (1, 'Portugal', 'Netherlands', 'Germany', 'Luxembourg'),
  (1, 'Spain', 'Norway', 'Netherlands', 'Ireland'),
  (1, 'Sweden', 'Portugal', 'Norway', 'Germany'),
  (2, 'Bulgaria', 'Croatia', 'Estonia', 'Switzerland'),
  (2, 'Croatia', 'Switzerland', 'Montenegro', 'Romania'),
  (2, 'Malta', 'Montenegro', 'Romania', 'Andorra'),
  (2, 'Montenegro', 'Malta', 'Bulgaria', 'Turkey'),
  (2, 'Romania', 'Croatia', 'Turkey', 'Malta'),
  (2, 'Switzerland', 'Bulgaria', 'Malta', 'Poland'),
  (2, 'Turkey', 'Romania', 'Croatia', 'Montenegro'),
  (2, 'Ukraine', 'Estonia', 'Switzerland', 'Slovakia'),
  (2, 'Estonia', 'Turkey', 'Poland', 'United Kingdom'),
  (2, 'Poland', 'Ukraine', 'United Kingdom', 'Estonia'),
  (2, 'United Kingdom', 'Poland', 'Slovakia', 'Albania'),
  (2, 'Albania', 'Slovakia', 'Ukraine', 'Andorra'),
  (2, 'Andorra', 'United Kingdom', 'Albania', 'Ukraine'),
  (2, 'Slovakia', 'Albania', 'Andorra', 'Bulgaria'),
  (3, 'Bosnia and Herzegovina', 'Czech Republic', 'Armenia', 'Cyprus'),
  (3, 'Czech Republic', 'Armenia', 'Belarus', ' Azerbaijan'),
  (3, 'Hungary', 'Bosnia and Herzegovina', 'Austria', 'Armenia'),
  (3, 'Liechtenstein', 'Czech Republic', ' Azerbaijan', 'Hungary'),
  (3, 'Latvia', ' Azerbaijan', 'Bosnia and Herzegovina', 'Austria'),
  (3, 'Lithuania', 'Latvia', 'Czech Republic', 'Belarus'),
  (3, 'Slovenia', 'Lithuania', 'Hungary', 'Vatican City'),
  (3, 'Vatican City', 'Liechtenstein', 'Cyprus', 'Bosnia and Herzegovina'),
  (3, 'Armenia', 'Hungary', 'Lithuania', 'Slovenia'),
  (3, 'Austria', 'Slovenia', 'Vatican City', 'Lithuania'),
  (3, 'Azerbaijan', 'Vatican City', 'Liechtenstein', 'Serbia'),
  (3, 'Cyprus', 'Belarus', 'Serbia', 'Latvia'),
  (3, 'Belarus', 'Serbia', 'Latvia', 'Liechtenstein'),
  (3, 'Serbia', 'Austria', 'Slovenia', 'Cyprus');
